[tool.poetry]
name = "trezor-user-env"
version = "0.0.0"
description = ""
authors = ["SatoshiLabs <info@satoshilabs.com>"]

[tool.poetry.dependencies]
python = "^3.11"
termcolor = "^1.1.0"
trezor = "^0.13.9"
websockets = "^10.1"
psutil = "^5.8.0"
Pillow = "^9.1.0"

[tool.poetry.dev-dependencies]
black = ">=22.3"
isort = "^5.10.1"
mypy = "^0.910"
flake8 = "^4.0.1"
pytest = "^6.2.5"
pytest-asyncio = "^0.16.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
